export const routes = {
  portals: {
    master: "/master",
    seller: "/seller",
    customer: "/login",
  },
  auth: {
    login: "/login",
    masterLogin: "/master",
    sellerLogin: "/seller",
    otpLogin: "/auth/otp-login",
    pinLogin: "/auth/pin-login",
    forgotPassword: "/auth/forgot-password",
  },
  superAdmin: {
    dashboard: "/super-admin/dashboard",
    users: "/super-admin/users",
    shopOwners: "/super-admin/shop-owners",
    shops: "/super-admin/shops",
    categories: "/super-admin/categories",
    brands: "/super-admin/brands",
    subCategories: "/super-admin/sub-categories",
    productTypes: "/super-admin/product-types",
    models: "/super-admin/models",
    productAttributes: "/super-admin/product-attributes",
    productCompatibilities: "/super-admin/product-compatibilities",
    products: "/super-admin/products",
    productApprovals: "/super-admin/product-approvals",
    reports: "/super-admin/reports",
    notifications: "/super-admin/notifications",
    settings: "/super-admin/settings",
  },
  shopOwner: {
    dashboard: "/shop-owner/dashboard",
    shops: "/shop-owner/shops",
    staff: "/shop-owner/staff",
    vendors: "/shop-owner/vendors",
    products: "/shop-owner/products",
    shopProducts: "/shop-owner/shop-products",
    purchases: "/shop-owner/purchases",
    purchaseReturns: "/shop-owner/purchase-returns",
    sales: "/shop-owner/sales",
    salesReturns: "/shop-owner/sales-returns",
    stockTransfers: "/shop-owner/stock-transfers",
    physicalStock: "/shop-owner/physical-stock",
    barcode: "/shop-owner/barcode",
    expenses: "/shop-owner/expenses",
    orders: "/shop-owner/orders",
    invoices: "/shop-owner/invoices",
    customers: "/shop-owner/customers",
    reports: "/shop-owner/reports",
    notifications: "/shop-owner/notifications",
    settings: "/shop-owner/settings",
  },
  shopStaff: {
    dashboard: "/shop-staff/dashboard",
    pos: "/shop-staff/pos",
    sales: "/shop-staff/sales",
    salesReturns: "/shop-staff/sales-returns",
    stock: "/shop-staff/stock",
    stockTransfers: "/shop-staff/stock-transfers",
    physicalStock: "/shop-staff/physical-stock",
    customers: "/shop-staff/customers",
    barcode: "/shop-staff/barcode",
    notifications: "/shop-staff/notifications",
  },
  customer: {
    home: "/customer/home",
    products: "/customer/products",
    productDetails: (id: string | number) => `/customer/products/${id}`,
    cart: "/customer/cart",
    checkout: "/customer/checkout",
    orders: "/customer/orders",
    orderDetails: (id: string | number) => `/customer/orders/${id}`,
    invoices: "/customer/invoices",
    wishlist: "/customer/wishlist",
    reviews: "/customer/reviews",
    profile: "/customer/profile",
    notifications: "/customer/notifications",
  },
  vendor: {
    dashboard: "/vendor/dashboard",
    profile: "/vendor/profile",
    purchaseOrders: "/vendor/purchase-orders",
    payments: "/vendor/payments",
    productsSupplied: "/vendor/products-supplied",
    reports: "/vendor/reports",
    notifications: "/vendor/notifications",
  },
};
